# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

VER	= $(subst ",,$(filter-out \#define CS_VERSION,$(shell grep CS_VERSION globals.h)))$(shell svnversion -n . | sed 's/.$$//' )
CS_CONFDIR = '\"/usr/local/etc\"'

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cogsi/code/oscam-svn/trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cogsi/code/oscam-svn/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"bin\" \"doc\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/cogsi/code/oscam-svn/trunk/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cogsi/code/oscam-svn/trunk/CMakeFiles /home/cogsi/code/oscam-svn/trunk/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cogsi/code/oscam-svn/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

######################################################################
#
#	LINUX native
#
######################################################################
i386-pc-linux:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst i386,$(shell uname --machine),$(subst cross-,,$@)) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DCS_CONFDIR=${CS_CONFDIR} -Winline -Wall -Wno-implicit-function-declaration -Wno-parentheses -finline-functions -fomit-frame-pointer -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=gcc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

######################################################################
#
#       MacOSX native
#
######################################################################
macosx-native:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_MACOSX -DNEED_DAEMON -DCS_NOSHM -DHAVE_PTHREAD_H -DUSE_PTHREAD -DCS_CONFDIR=${CS_CONFDIR} -Winline -Wall -Wno-implicit-function-declaration -Wno-parentheses -finline-functions -fomit-frame-pointer -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=gcc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

#=============================================================================
# Target rules for targets named csmodules

######################################################################
#
#	FreeBSD native
#
######################################################################
i386-pc-freebsd:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_FREEBSD -DBSD_COMP  -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=gcc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

######################################################################
#
#	FreeBSD 5.4 crosscompiler
#
######################################################################
cross-i386-pc-freebsd:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_FREEBSD -DBSD_COMP -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=i386-pc-freebsd5.4-gcc \
		DS_AR=i386-pc-freebsd5.4-ar \
		DS_LD=i386-pc-freebsd5.4-ld \
		DS_RL=i386-pc-freebsd5.4-ranlib \
		DS_ST=i386-pc-freebsd5.4-strip

######################################################################
#
#	Tuxbox crosscompiler
#
######################################################################
cross-powerpc-tuxbox-linux:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto -ldl" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DTUXBOX -DPPC -DCS_CONFDIR='\"/var/tuxbox/config\"' -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=powerpc-tuxbox-linux-gnu-gcc \
		DS_AR=powerpc-tuxbox-linux-gnu-ar \
		DS_LD=powerpc-tuxbox-linux-gnu-ld \
		DS_RL=powerpc-tuxbox-linux-gnu-ranlib \
		DS_ST=powerpc-tuxbox-linux-gnu-strip

cross-powerpc-tuxbox-linux-uclibc:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DTUXBOX -DPPC -DCS_CONFDIR='\"/var/tuxbox/config\"' -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=powerpc-tuxbox-linux-uclibc-gcc \
		DS_AR=powerpc-tuxbox-linux-uclibc-ar \
		DS_LD=powerpc-tuxbox-linux-uclibc-ld \
		DS_RL=powerpc-tuxbox-linux-uclibc-ranlib \
		DS_ST=powerpc-tuxbox-linux-uclibc-strip

# fast build rule for target.
csoscam/fast:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/build
.PHONY : csoscam/fast

######################################################################
#
#	sh4 crosscompiler
#
######################################################################
cross-sh4-linux:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DSH4 -DTUXBOX -DCS_CONFDIR='\"/var/tuxbox/config\"' -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=/opt/STM/STLinux-2.0/devkit/sh4/bin/sh4-linux-gcc \
		DS_AR=/opt/STM/STLinux-2.0/devkit/sh4/bin/sh4-linux-ar \
		DS_LD=/opt/STM/STLinux-2.0/devkit/sh4/bin/sh4-linux-ld \
		DS_RL=/opt/STM/STLinux-2.0/devkit/sh4/bin/sh4-linux-ranlib \
		DS_ST=/opt/STM/STLinux-2.0/devkit/sh4/bin/sh4-linux-strip

######################################################################
#
#	Cygwin crosscompiler
#
######################################################################
cross-i386-pc-cygwin:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_CYGWIN32 -DCS_CONFDIR=${CS_CONFDIR} -static -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=i686-pc-cygwin-gcc \
		DS_AR=i686-pc-cygwin-ar \
		DS_LD=i686-pc-cygwin-ld \
		DS_RL=i686-pc-cygwin-ranlib \
		DS_ST=i686-pc-cygwin-strip

######################################################################
#
#	Cygwin native
#
######################################################################
i386-pc-cygwin:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_CYGWIN32 -DCS_CONFDIR=${CS_CONFDIR} -I /tmp/include -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=gcc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

######################################################################
#
#	Solaris 7 crosscompiler
#
######################################################################
cross-sparc-sun-solaris2.7:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_SOLARIS -DOS_SOLARIS7 -DBSD_COMP -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="-lsocket" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=sparc-sun-solaris2.7-gcc \
		DS_AR=sparc-sun-solaris2.7-ar \
		DS_LD=sparc-sun-solaris2.7-ld \
		DS_RL=sparc-sun-solaris2.7-ranlib \
		DS_ST=sparc-sun-solaris2.7-strip

######################################################################
#
#	OpenSolaris native compiler
#
######################################################################
opensolaris:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto -lnsl" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_SOLARIS -DOS_SOLARIS7 -DBSD_COMP -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="-lsocket" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=gcc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

######################################################################
#
#	AIX 4.2 crosscompiler
#
######################################################################
cross-rs6000-ibm-aix4.2:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthreads" \
		DS_OPTS="-O2 -DOS_AIX -DOS_AIX42 -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=rs6000-ibm-aix4.2-gcc \
		DS_AR=rs6000-ibm-aix4.2-ar \
		DS_LD=rs6000-ibm-aix4.2-ld \
		DS_RL=rs6000-ibm-aix4.2-ranlib \
		DS_ST=rs6000-ibm-aix4.2-strip

######################################################################
#
#	IRIX 6.5 crosscompiler
#
######################################################################
cross-mips-sgi-irix6.5:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_IRIX -DOS_IRIX65 -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mips-sgi-irix6.5-gcc \
		DS_AR=mips-sgi-irix6.5-ar \
		DS_LD=mips-sgi-irix6.5-ld \
		DS_RL=mips-sgi-irix6.5-ranlib \
		DS_ST=mips-sgi-irix6.5-strip

cross-mipsel-router-linux-uclibc: cross-mipsel-router-linux-uclibc929
######################################################################
#
#	Linux MIPS(LE) crosscompiler with ucLibc 0.9.27
#
######################################################################
cross-mipsel-router-linux-uclibc927:
	@-mipsel-linux-uclibc-setlib 0.9.27
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DMIPSEL -DUCLIBC -DUSE_GPIO -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mipsel-linux-uclibc-gcc \
		DS_AR=mipsel-linux-uclibc-ar \
		DS_LD=mipsel-linux-uclibc-ld \
		DS_RL=mipsel-linux-uclibc-ranlib \
		DS_ST=mipsel-linux-uclibc-strip

######################################################################
#
#	Linux MIPS(LE) crosscompiler with ucLibc 0.9.28
#
######################################################################
cross-mipsel-router-linux-uclibc928:
	@-mipsel-linux-uclibc-setlib 0.9.28
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DMIPSEL -DUCLIBC -DUSE_GPIO -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mipsel-linux-uclibc-gcc \
		DS_AR=mipsel-linux-uclibc-ar \
		DS_LD=mipsel-linux-uclibc-ld \
		DS_RL=mipsel-linux-uclibc-ranlib \
		DS_ST=mipsel-linux-uclibc-strip

######################################################################
#
#	Linux MIPS(LE) crosscompiler with ucLibc 0.9.29
#
######################################################################
cross-mipsel-router-linux-uclibc929:
	@-mipsel-linux-uclibc-setlib 0.9.29
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DMIPSEL -DUCLIBC -DUSE_GPIO -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mipsel-linux-uclibc-gcc \
		DS_AR=mipsel-linux-uclibc-ar \
		DS_LD=mipsel-linux-uclibc-ld \
		DS_RL=mipsel-linux-uclibc-ranlib \
		DS_ST=mipsel-linux-uclibc-strip

######################################################################
#
#	Linux MIPS(LE) crosscompiler with ucLibc 0.9.29 (static)
#
######################################################################
cross-mipsel-router-linux-uclibc929-static:
	@-mipsel-linux-uclibc-setlib 0.9.29
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DMIPSEL -DUCLIBC -DUSE_GPIO -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="-static" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mipsel-linux-uclibc-gcc \
		DS_AR=mipsel-linux-uclibc-ar \
		DS_LD=mipsel-linux-uclibc-ld \
		DS_RL=mipsel-linux-uclibc-ranlib \
		DS_ST=mipsel-linux-uclibc-strip

######################################################################
#
#	Linux MIPS(LE) crosscompiler for La Fonera 2.0
#
######################################################################
cross-mipsel-fonera2:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-Lopenssl-lib -lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-Iopenssl-include -O2 -DOS_LINUX -DMIPSEL -DUCLIBC -DCS_CONFDIR=${CS_CONFDIR} -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mips-linux-gcc \
		DS_AR=mips-linux-ar \
		DS_LD=mips-linux-ld \
		DS_RL=mips-linux-ranlib \
		DS_ST=mips-linux-strip

######################################################################
#
#	Linux MIPS(LE) crosscompiler with glibc (DM7025)
#
######################################################################
cross-mipsel-tuxbox-linux-glibc:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DTUXBOX -DMIPSEL -DCS_CONFDIR='\"/var/tuxbox/config\"' -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mipsel-linux-glibc-gcc \
		DS_AR=mipsel-linux-glibc-ar \
		DS_LD=mipsel-linux-glibc-ld \
		DS_RL=mipsel-linux-glibc-ranlib \
		DS_ST=mipsel-linux-glibc-strip

cross-mipsel-tuxbox-linux:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="-lcrypto" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_LINUX -DTUXBOX -DMIPSEL -DCS_CONFDIR='\"/var/tuxbox/config\"' -static-libgcc -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=mipsel-linux-gcc \
		DS_AR=mipsel-linux-ar \
		DS_LD=mipsel-linux-ld \
		DS_RL=mipsel-linux-ranlib \
		DS_ST=mipsel-linux-strip

######################################################################
#
#	HP/UX 10.20 native
#
######################################################################
hppa1.1-hp-hpux10.20:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_HPUX -DOS_HPUX10 -D_XOPEN_SOURCE_EXTENDED -DCS_CONFDIR=${CS_CONFDIR} -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=gcc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

######################################################################
#
#	OSF5.1 native
#
######################################################################
alpha-dec-osf5.1:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP=$(subst cross-,,$@) \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-O2 -DOS_OSF -DOS_OSF5 -DCS_CONFDIR=${CS_CONFDIR} -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		XDS_CFLAGS="-I/usr/include -c" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_CC=cc \
		DS_AR=ar \
		DS_LD=ld \
		DS_RL=ranlib \
		DS_ST=strip

######################################################################
#
#	ARM crosscompiler (big-endian)
#
######################################################################
cross-arm-nslu2-linux:
	@-$(MAKE) --no-print-directory \
		-f Maketype TYP="$(subst cross-,,$@)" \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-DOS_LINUX -O2 -DARM -DALIGNMENT -DCS_CONFDIR=${CS_CONFDIR} -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_AWK="awk" \
		DS_CC="armv5b-softfloat-linux-gcc" \
		DS_AR="armv5b-softfloat-linux-ar" \
		DS_LD="armv5b-softfloat-linux-ld" \
		DS_RL="armv5b-softfloat-linux-ranlib" \
		DS_ST="armv5b-softfloat-linux-strip"

######################################################################
#
#	ARM crosscompiler (big-endian)
#
######################################################################
cross-armBE-unkown-linux:
	-$(MAKE) --no-print-directory \
		-f Maketype TYP="$(subst cross-,,$@)" \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-DOS_LINUX -O2 -DARM -DALIGNMENT -DCS_CONFDIR=${CS_CONFDIR} -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_AWK="awk" \
		DS_CC="arm-linux-gcc -mbig-endian" \
		DS_AR="arm-linux-ar" \
		DS_LD="arm-linux-ld -EB" \
		DS_RL="arm-linux-ranlib" \
		DS_ST="arm-linux-strip"

######################################################################
#
#	ARM crosscompiler (little-endian)
#
######################################################################
cross-armLE-unkown-linux:
	-$(MAKE) --no-print-directory \
		-f Maketype TYP="$(subst cross-,,$@)" \
		OS_LIBS="" \
		OS_CULI="-lncurses" \
		OS_PTLI="-lpthread" \
		DS_OPTS="-DOS_LINUX -O2 -DARM -DALIGNMENT -DCS_CONFDIR=${CS_CONFDIR}  -D'CS_SVN_VERSION="'"$(shell svnversion -n . | sed 's/.$$//' )"'"'" \
		DS_CFLAGS="-c" \
		DS_LDFLAGS="" \
		DS_ARFLAGS="-rvsl" \
		DS_AWK="awk" \
		DS_CC="arm-linux-gcc -mlittle-endian" \
		DS_AR="arm-linux-ar" \
		DS_LD="arm-linux-ld -EL" \
		DS_RL="arm-linux-ranlib" \
		DS_ST="arm-linux-strip"
