# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/trunk4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/trunk4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"bin\" \"doc\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /tmp/trunk4/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/trunk4/CMakeFiles /tmp/trunk4/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/trunk4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named csmodules

# Build rule for target.
csmodules: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csmodules
.PHONY : csmodules

# fast build rule for target.
csmodules/fast:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/build
.PHONY : csmodules/fast

#=============================================================================
# Target rules for targets named csoscam

# Build rule for target.
csoscam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csoscam
.PHONY : csoscam

# fast build rule for target.
csoscam/fast:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/build
.PHONY : csoscam/fast

#=============================================================================
# Target rules for targets named csreaders

# Build rule for target.
csreaders: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csreaders
.PHONY : csreaders

# fast build rule for target.
csreaders/fast:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/build
.PHONY : csreaders/fast

#=============================================================================
# Target rules for targets named oscam

# Build rule for target.
oscam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 oscam
.PHONY : oscam

# fast build rule for target.
oscam/fast:
	$(MAKE) -f CMakeFiles/oscam.dir/build.make CMakeFiles/oscam.dir/build
.PHONY : oscam/fast

#=============================================================================
# Target rules for targets named csctapi

# Build rule for target.
csctapi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csctapi
.PHONY : csctapi

# fast build rule for target.
csctapi/fast:
	$(MAKE) -f csctapi/CMakeFiles/csctapi.dir/build.make csctapi/CMakeFiles/csctapi.dir/build
.PHONY : csctapi/fast

#=============================================================================
# Target rules for targets named cscrypt

# Build rule for target.
cscrypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cscrypt
.PHONY : cscrypt

# fast build rule for target.
cscrypt/fast:
	$(MAKE) -f cscrypt/CMakeFiles/cscrypt.dir/build.make cscrypt/CMakeFiles/cscrypt.dir/build
.PHONY : cscrypt/fast

# target to build an object file
module-camd33.o:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-camd33.o
.PHONY : module-camd33.o

# target to preprocess a source file
module-camd33.i:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-camd33.i
.PHONY : module-camd33.i

# target to generate assembly for a file
module-camd33.s:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-camd33.s
.PHONY : module-camd33.s

# target to build an object file
module-camd35.o:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-camd35.o
.PHONY : module-camd35.o

# target to preprocess a source file
module-camd35.i:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-camd35.i
.PHONY : module-camd35.i

# target to generate assembly for a file
module-camd35.s:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-camd35.s
.PHONY : module-camd35.s

# target to build an object file
module-monitor.o:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-monitor.o
.PHONY : module-monitor.o

# target to preprocess a source file
module-monitor.i:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-monitor.i
.PHONY : module-monitor.i

# target to generate assembly for a file
module-monitor.s:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-monitor.s
.PHONY : module-monitor.s

# target to build an object file
module-newcamd.o:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-newcamd.o
.PHONY : module-newcamd.o

# target to preprocess a source file
module-newcamd.i:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-newcamd.i
.PHONY : module-newcamd.i

# target to generate assembly for a file
module-newcamd.s:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-newcamd.s
.PHONY : module-newcamd.s

# target to build an object file
module-radegast.o:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-radegast.o
.PHONY : module-radegast.o

# target to preprocess a source file
module-radegast.i:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-radegast.i
.PHONY : module-radegast.i

# target to generate assembly for a file
module-radegast.s:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-radegast.s
.PHONY : module-radegast.s

# target to build an object file
module-serial.o:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-serial.o
.PHONY : module-serial.o

# target to preprocess a source file
module-serial.i:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-serial.i
.PHONY : module-serial.i

# target to generate assembly for a file
module-serial.s:
	$(MAKE) -f CMakeFiles/csmodules.dir/build.make CMakeFiles/csmodules.dir/module-serial.s
.PHONY : module-serial.s

# target to build an object file
oscam-ac.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-ac.o
.PHONY : oscam-ac.o

# target to preprocess a source file
oscam-ac.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-ac.i
.PHONY : oscam-ac.i

# target to generate assembly for a file
oscam-ac.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-ac.s
.PHONY : oscam-ac.s

# target to build an object file
oscam-chk.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-chk.o
.PHONY : oscam-chk.o

# target to preprocess a source file
oscam-chk.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-chk.i
.PHONY : oscam-chk.i

# target to generate assembly for a file
oscam-chk.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-chk.s
.PHONY : oscam-chk.s

# target to build an object file
oscam-config.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-config.o
.PHONY : oscam-config.o

# target to preprocess a source file
oscam-config.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-config.i
.PHONY : oscam-config.i

# target to generate assembly for a file
oscam-config.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-config.s
.PHONY : oscam-config.s

# target to build an object file
oscam-log.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-log.o
.PHONY : oscam-log.o

# target to preprocess a source file
oscam-log.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-log.i
.PHONY : oscam-log.i

# target to generate assembly for a file
oscam-log.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-log.s
.PHONY : oscam-log.s

# target to build an object file
oscam-nano.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-nano.o
.PHONY : oscam-nano.o

# target to preprocess a source file
oscam-nano.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-nano.i
.PHONY : oscam-nano.i

# target to generate assembly for a file
oscam-nano.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-nano.s
.PHONY : oscam-nano.s

# target to build an object file
oscam-reader.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-reader.o
.PHONY : oscam-reader.o

# target to preprocess a source file
oscam-reader.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-reader.i
.PHONY : oscam-reader.i

# target to generate assembly for a file
oscam-reader.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-reader.s
.PHONY : oscam-reader.s

# target to build an object file
oscam-simples.o:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-simples.o
.PHONY : oscam-simples.o

# target to preprocess a source file
oscam-simples.i:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-simples.i
.PHONY : oscam-simples.i

# target to generate assembly for a file
oscam-simples.s:
	$(MAKE) -f CMakeFiles/csoscam.dir/build.make CMakeFiles/csoscam.dir/oscam-simples.s
.PHONY : oscam-simples.s

# target to build an object file
oscam.o:
	$(MAKE) -f CMakeFiles/oscam.dir/build.make CMakeFiles/oscam.dir/oscam.o
.PHONY : oscam.o

# target to preprocess a source file
oscam.i:
	$(MAKE) -f CMakeFiles/oscam.dir/build.make CMakeFiles/oscam.dir/oscam.i
.PHONY : oscam.i

# target to generate assembly for a file
oscam.s:
	$(MAKE) -f CMakeFiles/oscam.dir/build.make CMakeFiles/oscam.dir/oscam.s
.PHONY : oscam.s

# target to build an object file
reader-common.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-common.o
.PHONY : reader-common.o

# target to preprocess a source file
reader-common.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-common.i
.PHONY : reader-common.i

# target to generate assembly for a file
reader-common.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-common.s
.PHONY : reader-common.s

# target to build an object file
reader-conax.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-conax.o
.PHONY : reader-conax.o

# target to preprocess a source file
reader-conax.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-conax.i
.PHONY : reader-conax.i

# target to generate assembly for a file
reader-conax.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-conax.s
.PHONY : reader-conax.s

# target to build an object file
reader-cryptoworks.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-cryptoworks.o
.PHONY : reader-cryptoworks.o

# target to preprocess a source file
reader-cryptoworks.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-cryptoworks.i
.PHONY : reader-cryptoworks.i

# target to generate assembly for a file
reader-cryptoworks.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-cryptoworks.s
.PHONY : reader-cryptoworks.s

# target to build an object file
reader-irdeto.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-irdeto.o
.PHONY : reader-irdeto.o

# target to preprocess a source file
reader-irdeto.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-irdeto.i
.PHONY : reader-irdeto.i

# target to generate assembly for a file
reader-irdeto.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-irdeto.s
.PHONY : reader-irdeto.s

# target to build an object file
reader-nds.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-nds.o
.PHONY : reader-nds.o

# target to preprocess a source file
reader-nds.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-nds.i
.PHONY : reader-nds.i

# target to generate assembly for a file
reader-nds.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-nds.s
.PHONY : reader-nds.s

# target to build an object file
reader-seca.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-seca.o
.PHONY : reader-seca.o

# target to preprocess a source file
reader-seca.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-seca.i
.PHONY : reader-seca.i

# target to generate assembly for a file
reader-seca.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-seca.s
.PHONY : reader-seca.s

# target to build an object file
reader-viaccess.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-viaccess.o
.PHONY : reader-viaccess.o

# target to preprocess a source file
reader-viaccess.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-viaccess.i
.PHONY : reader-viaccess.i

# target to generate assembly for a file
reader-viaccess.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-viaccess.s
.PHONY : reader-viaccess.s

# target to build an object file
reader-videoguard2.o:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-videoguard2.o
.PHONY : reader-videoguard2.o

# target to preprocess a source file
reader-videoguard2.i:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-videoguard2.i
.PHONY : reader-videoguard2.i

# target to generate assembly for a file
reader-videoguard2.s:
	$(MAKE) -f CMakeFiles/csreaders.dir/build.make CMakeFiles/csreaders.dir/reader-videoguard2.s
.PHONY : reader-videoguard2.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... csmodules"
	@echo "... csoscam"
	@echo "... csreaders"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... oscam"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... csctapi"
	@echo "... cscrypt"
	@echo "... module-camd33.o"
	@echo "... module-camd33.i"
	@echo "... module-camd33.s"
	@echo "... module-camd35.o"
	@echo "... module-camd35.i"
	@echo "... module-camd35.s"
	@echo "... module-monitor.o"
	@echo "... module-monitor.i"
	@echo "... module-monitor.s"
	@echo "... module-newcamd.o"
	@echo "... module-newcamd.i"
	@echo "... module-newcamd.s"
	@echo "... module-radegast.o"
	@echo "... module-radegast.i"
	@echo "... module-radegast.s"
	@echo "... module-serial.o"
	@echo "... module-serial.i"
	@echo "... module-serial.s"
	@echo "... oscam-ac.o"
	@echo "... oscam-ac.i"
	@echo "... oscam-ac.s"
	@echo "... oscam-chk.o"
	@echo "... oscam-chk.i"
	@echo "... oscam-chk.s"
	@echo "... oscam-config.o"
	@echo "... oscam-config.i"
	@echo "... oscam-config.s"
	@echo "... oscam-log.o"
	@echo "... oscam-log.i"
	@echo "... oscam-log.s"
	@echo "... oscam-nano.o"
	@echo "... oscam-nano.i"
	@echo "... oscam-nano.s"
	@echo "... oscam-reader.o"
	@echo "... oscam-reader.i"
	@echo "... oscam-reader.s"
	@echo "... oscam-simples.o"
	@echo "... oscam-simples.i"
	@echo "... oscam-simples.s"
	@echo "... oscam.o"
	@echo "... oscam.i"
	@echo "... oscam.s"
	@echo "... reader-common.o"
	@echo "... reader-common.i"
	@echo "... reader-common.s"
	@echo "... reader-conax.o"
	@echo "... reader-conax.i"
	@echo "... reader-conax.s"
	@echo "... reader-cryptoworks.o"
	@echo "... reader-cryptoworks.i"
	@echo "... reader-cryptoworks.s"
	@echo "... reader-irdeto.o"
	@echo "... reader-irdeto.i"
	@echo "... reader-irdeto.s"
	@echo "... reader-nds.o"
	@echo "... reader-nds.i"
	@echo "... reader-nds.s"
	@echo "... reader-seca.o"
	@echo "... reader-seca.i"
	@echo "... reader-seca.s"
	@echo "... reader-viaccess.o"
	@echo "... reader-viaccess.i"
	@echo "... reader-viaccess.s"
	@echo "... reader-videoguard2.o"
	@echo "... reader-videoguard2.i"
	@echo "... reader-videoguard2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

