.TH oscam.ird 5
.SH NAME
\fBoscam.ird\fR - Irdeto guessing table for oscam
.SH SYNOPSIS
Irdeto guessing table
.SH DESCRIPTIONS
.PP
\fB<byte3>\fP:\fB<byte4-7>\fP:\fB<CAID>\fP:\fB<SID>\fP
.RS 3n
Irdeto guessing table by signature
.RE
.SH EXAMPLES
 12:0000000a:12ab:cd01
.SH "SEE ALSO"
\fBoscam\fR(1), \fBoscam.conf\fR(5), \fBoscam.user\fR(5), \fBoscam.server\fR(5), \fBoscam.srvid\fR(5), \fBoscam.guess\fR(5), \fBoscam.cert\fR(5), \fBoscam.services\fR(5), \fBoscam.ac\fR(5)