.TH oscam.srvid 5
.SH NAME
\fBoscam.srvid\fR - service ID configuration file for oscam
.SH SYNOPSIS
service ID mappings
.SH DESCRIPTIONS
.PP
\fB<srvid>\fP:\fB<name of service>\fP
.RS 3n
mapping between service ID and name of service
.RE
.SH EXAMPLE
 000A:my service 1
 00FF:my service 2
.SH "SEE ALSO"
\fBoscam\fR(1), \fBoscam.conf\fR(5), \fBoscam.user\fR(5) \fBoscam.server\fR(5), \fBoscam.guess\fR(5), \fBoscam.cert\fR(5), \fBoscam.services\fR(5), \fBoscam.ird\fR(5), \fBoscam.ac\fR(5)
